services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nodeapp:
    build: .
    container_name: nodeapp
    environment:
      DB_HOST: locahost
      DB_USER: root
      DB_PASSWORD: root_password
      DB_DATABASE: mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql-data:
