services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  nodeapp:
    build: .
    container_name: nodeapp
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root_password
      DB_DATABASE: mydatabase
    ports:
      - "3000:3000"
    

  frontend:
    build:
      context: ../frontendmind
    container_name: frontend
    ports:
      - "3030:3030"
    

volumes:
  mysql-volume:
    driver: local